export const QUERY_KEYS = {
   IS_AUTH_CHECK: 'isAuthCheck',
   GET_ALL_PRODUCTS: 'getallproducts',
   GET_ALL_USERS: 'getallusers',
   GET_PRODUCTS_BY_STATUS: 'getproductsbystatus',
   GET_PRODUCTS_BY_TYPE: 'getproductsbytype',
   GET_PRODUCT_BY_SLUG: 'getproductbyslug',
   GET_ALL_CATEGORY: 'getallcategory',
   GET_CATEGORY_BY_SLUG: 'getcategorybyslug',
   FETCH_TEMPLATES: 'fetchtemplates',
   GET_ALL_OFFERS: 'getalloffers',
   GET_OFFER_BY_SLUG: 'getofferbyslug',
   GET_ORDERS_BY_USER_ID: 'getordersbyuserid',
   GET_OFFERS: 'getoffers',
   GET_ALL_ORDERS_BY_STATUS: 'getallordersbystatus',
   GET_ALL_ORDERS: 'getallorders',
   GET_PENDING_PROCESSING_ORDERS: 'getpendingprocessingorders',
   UPDATE_ORDER_ACTION: 'updateorderaction',
   GET_NOTIFICATION_COUNT: 'getnotificationcount',
   GET_ALL_RATINGS: 'getallratings',
   GET_SEARCH_PRODUCTS: 'getsearchproducts',
}